"""add account_number to accounts

Revision ID: 0e8536ee7d69
Revises: 1470bfed08af
Create Date: 2025-05-16 00:08:10.252004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8536ee7d69'
down_revision = '1470bfed08af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
