"""Aumentar tamaño de password_hash

Revision ID: 402312da05c1
Revises: 0755aafc0902
Create Date: 2025-05-10 00:24:13.410363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402312da05c1'
down_revision = '0755aafc0902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
