"""columna admin

Revision ID: 98921692b2f2
Revises: 0e8536ee7d69
Create Date: 2025-05-26 00:06:57.598887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98921692b2f2'
down_revision = '0e8536ee7d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
